[project]
name = "niconico-seiga"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.12.3",
    "browser-cookie3>=0.20.1",
    "httpx>=0.28.1",
    "requests>=2.32.3",
    "tqdm>=4.67.1",
]
